name: Python CI

on : 
  push:
      branches:
        - ci/issue-47
  
jobs :
  build:
    runs-on : ubuntu-latest

    steps :
    - name : Checkout code
      uses : actions/checkout@v3

    - name : Set up Python
      uses : actions/setup-python@v3
      with :
        python-version: 3.10.12

    - name : Install dependencies
      run :
        pip install -r requirements.txt
        pip install pytest pylint

    - name : Run unit tests
      run : pytest ./test_models.py

    - name : Lint code
      run : pylint **/*.py
